checks:
  php: true

build:
  nodes:
    analysis:
      image: default-bionic
      environment:
        php: 8.1
      tests:
        override: [php-scrutinizer-run]

filter:
  paths: ["src/*", "tests/*"]
  excluded_paths:
    - "tests/mock/"

tools:
  external_code_coverage: true
