<?php

namespace Firesphere\CSPHeaders\View;

use SilverStripe\Core\Flushable;
use SilverStripe\View\Requirements;
use SilverStripe\View\Requirements_Backend;

class CSPRequirements extends Requirements implements Flushable
{
    public static function insertJSTags($js, $identifier = null, $options = [])
    {
        static::backend()->insertJSTags($js, $identifier, $options);
    }

    /**
     * @return Requirements_Backend|CSPBackend
     */
    public static function backend()
    {
        return parent::backend(); // TODO: Change the autogenerated stub
    }

    public static function insertJCSSTags($css, $identifier = null, $options = [])
    {
        static::backend()->insertCSSTags($css, $identifier, $options);
    }
}
